src/Entity/Interview.php
<?php

namespace App\Entity;

use App\Repository\InterviewRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InterviewRepository::class)]
class Interview
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $fecha = null;

    #[ORM\Column(length: 255)]
    private ?string $ciudad = null;

    #[ORM\Column(length: 255)]
    private ?string $h_crimen = null;

    #[ORM\Column(length: 255)]
    private ?string $testigo = null;

    #[ORM\Column(length: 255)]
    private ?string $t_crimen = null;

    #[ORM\Column(length: 1000)]
    private ?string $transcripcion = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFecha(): ?string
    {
        return $this->fecha;
    }

    public function setFecha(string $fecha): static
    {
        $this->fecha = $fecha;

        return $this;
    }

    public function getCiudad(): ?string
    {
        return $this->ciudad;
    }

    public function setCiudad(string $ciudad): static
    {
        $this->ciudad = $ciudad;

        return $this;
    }

    public function getHCrimen(): ?string
    {
        return $this->h_crimen;
    }

    public function setHCrimen(string $h_crimen): static
    {
        $this->h_crimen = $h_crimen;

        return $this;
    }

    public function getTestigo(): ?string
    {
        return $this->testigo;
    }

    public function setTestigo(string $testigo): static
    {
        $this->testigo = $testigo;

        return $this;
    }

    public function getTCrimen(): ?string
    {
        return $this->t_crimen;
    }

    public function setTCrimen(string $t_crimen): static
    {
        $this->t_crimen = $t_crimen;

        return $this;
    }

    public function getTranscripcion(): ?string
    {
        return $this->transcripcion;
    }

    public function setTranscripcion(string $transcripcion): static
    {
        $this->transcripcion = $transcripcion;

        return $this;
    }
}

src/Form/InterviewType.php
<?php

namespace App\Form;

use App\Entity\Interview;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InterviewType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('fecha')
            ->add('ciudad')
            ->add('h_crimen')
            ->add('testigo')
            ->add('t_crimen')
            ->add('transcripcion')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Interview::class,
        ]);
    }
}

src/Controller/InterviewController.php
<?php

namespace App\Controller;

use App\Entity\Interview;
use App\Form\InterviewType;
use App\Repository\InterviewRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/interview')]
class InterviewController extends AbstractController
{
    #[Route('/', name: 'app_interview_index', methods: ['GET'])]
    public function index(InterviewRepository $interviewRepository): Response
    {
        return $this->render('interview/index.html.twig', [
            'interviews' => $interviewRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_interview_new', methods: ['GET', 'POST'])]
    public function new(Request $request, InterviewRepository $interviewRepository): Response
    {
        $interview = new Interview();
        $form = $this->createForm(InterviewType::class, $interview);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $interviewRepository->save($interview, true);

            return $this->redirectToRoute('app_interview_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('interview/new.html.twig', [
            'interview' => $interview,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_interview_show', methods: ['GET'])]
    public function show(Interview $interview): Response
    {
        return $this->render('interview/show.html.twig', [
            'interview' => $interview,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_interview_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Interview $interview, InterviewRepository $interviewRepository): Response
    {
        $form = $this->createForm(InterviewType::class, $interview);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $interviewRepository->save($interview, true);

            return $this->redirectToRoute('app_interview_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('interview/edit.html.twig', [
            'interview' => $interview,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_interview_delete', methods: ['POST'])]
    public function delete(Request $request, Interview $interview, InterviewRepository $interviewRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$interview->getId(), $request->request->get('_token'))) {
            $interviewRepository->remove($interview, true);
        }

        return $this->redirectToRoute('app_interview_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/interview/_delete_form.html.twig
<form method="post" action="{{ path('app_interview_delete', {'id': interview.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ interview.id) }}">
    <button class="btn">Delete</button>
</form>

templates/interview/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/interview/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Interview{% endblock %}

{% block body %}
    <h1>Edit Interview</h1>

    {{ include('interview/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_interview_index') }}">back to list</a>

    {{ include('interview/_delete_form.html.twig') }}
{% endblock %}

templates/interview/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Interview{% endblock %}

{% block body %}
{{parent()}}
    <div class="container">
        <h1>Interview</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Fecha</th>
                    <th>Ciudad</th>
                    <th>H_crimen</th>
                    <th>Testigo</th>
                    <th>T_crimen</th>
                    <th>Transcripcion</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
            {% for interview in interviews %}
                <tr>
                    <td>{{ interview.id }}</td>
                    <td>{{ interview.fecha }}</td>
                    <td>{{ interview.ciudad }}</td>
                    <td>{{ interview.hCrimen }}</td>
                    <td>{{ interview.testigo }}</td>
                    <td>{{ interview.tCrimen }}</td>
                    <td>{{ interview.transcripcion }}</td>
                    <td>
                        <a href="{{ path('app_interview_show', {'id': interview.id}) }}">show</a>
                        <a href="{{ path('app_interview_edit', {'id': interview.id}) }}">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="8">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <a href="{{ path('app_interview_new') }}">Create new</a>
{% endblock %}

templates/interview/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Interview{% endblock %}

{% block body %}
    <h1>Create new Interview</h1>

    {{ include('interview/_form.html.twig') }}

    <a href="{{ path('app_interview_index') }}">back to list</a>
{% endblock %}

templates/interview/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Interview{% endblock %}

{% block body %}
    <h1>Interview</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ interview.id }}</td>
            </tr>
            <tr>
                <th>Fecha</th>
                <td>{{ interview.fecha }}</td>
            </tr>
            <tr>
                <th>Ciudad</th>
                <td>{{ interview.ciudad }}</td>
            </tr>
            <tr>
                <th>H_crimen</th>
                <td>{{ interview.hCrimen }}</td>
            </tr>
            <tr>
                <th>Testigo</th>
                <td>{{ interview.testigo }}</td>
            </tr>
            <tr>
                <th>T_crimen</th>
                <td>{{ interview.tCrimen }}</td>
            </tr>
            <tr>
                <th>Transcripcion</th>
                <td>{{ interview.transcripcion }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_interview_index') }}">back to list</a>

    <a href="{{ path('app_interview_edit', {'id': interview.id}) }}">edit</a>

    {{ include('interview/_delete_form.html.twig') }}
{% endblock %}