src/Entity/Biometric.php
<?php

namespace App\Entity;

use App\Repository\BiometricRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BiometricRepository::class)]
class Biometric
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nombre = null;

    #[ORM\Column(length: 255)]
    private ?string $c_ojos = null;

    #[ORM\Column(length: 255)]
    private ?string $c_cabello = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getCOjos(): ?string
    {
        return $this->c_ojos;
    }

    public function setCOjos(string $c_ojos): static
    {
        $this->c_ojos = $c_ojos;

        return $this;
    }

    public function getCCabello(): ?string
    {
        return $this->c_cabello;
    }

    public function setCCabello(string $c_cabello): static
    {
        $this->c_cabello = $c_cabello;

        return $this;
    }
}

src/Form/BiometricType.php
<?php

namespace App\Form;

use App\Entity\Biometric;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BiometricType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nombre')
            ->add('c_ojos')
            ->add('c_cabello')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Biometric::class,
        ]);
    }
}

src/Controller/BiometricController.php
<?php

namespace App\Controller;

use App\Entity\Biometric;
use App\Form\BiometricType;
use App\Repository\BiometricRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/biometric')]
class BiometricController extends AbstractController
{
    #[Route('/', name: 'app_biometric_index', methods: ['GET'])]
    public function index(BiometricRepository $biometricRepository): Response
    {
        return $this->render('biometric/index.html.twig', [
            'biometrics' => $biometricRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_biometric_new', methods: ['GET', 'POST'])]
    public function new(Request $request, BiometricRepository $biometricRepository): Response
    {
        $biometric = new Biometric();
        $form = $this->createForm(BiometricType::class, $biometric);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $biometricRepository->save($biometric, true);

            return $this->redirectToRoute('app_biometric_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('biometric/new.html.twig', [
            'biometric' => $biometric,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_biometric_show', methods: ['GET'])]
    public function show(Biometric $biometric): Response
    {
        return $this->render('biometric/show.html.twig', [
            'biometric' => $biometric,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_biometric_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Biometric $biometric, BiometricRepository $biometricRepository): Response
    {
        $form = $this->createForm(BiometricType::class, $biometric);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $biometricRepository->save($biometric, true);

            return $this->redirectToRoute('app_biometric_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('biometric/edit.html.twig', [
            'biometric' => $biometric,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_biometric_delete', methods: ['POST'])]
    public function delete(Request $request, Biometric $biometric, BiometricRepository $biometricRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$biometric->getId(), $request->request->get('_token'))) {
            $biometricRepository->remove($biometric, true);
        }

        return $this->redirectToRoute('app_biometric_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/biometric/_delete_form.html.twig
<form method="post" action="{{ path('app_biometric_delete', {'id': biometric.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ biometric.id) }}">
    <button class="btn">Delete</button>
</form>

templates/biometric/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/biometric/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Biometric{% endblock %}

{% block body %}
    <h1>Edit Biometric</h1>

    {{ include('biometric/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_biometric_index') }}">back to list</a>

    {{ include('biometric/_delete_form.html.twig') }}
{% endblock %}

templates/biometric/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Biometric{% endblock %}

{% block body %}
{{parent()}}
    <div class="container">
        <h1>Biometric</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>C_ojos</th>
                    <th>C_cabello</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
            {% for biometric in biometrics %}
                <tr>
                    <td>{{ biometric.id }}</td>
                    <td>{{ biometric.nombre }}</td>
                    <td>{{ biometric.cOjos }}</td>
                    <td>{{ biometric.cCabello }}</td>
                    <td>
                        <a href="{{ path('app_biometric_show', {'id': biometric.id}) }}">show</a>
                        <a href="{{ path('app_biometric_edit', {'id': biometric.id}) }}">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <a href="{{ path('app_biometric_new') }}">Create new</a>
{% endblock %}

templates/biometric/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Biometric{% endblock %}

{% block body %}
    <h1>Create new Biometric</h1>

    {{ include('biometric/_form.html.twig') }}

    <a href="{{ path('app_biometric_index') }}">back to list</a>
{% endblock %}

templates/biometric/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Biometric{% endblock %}

{% block body %}
    <h1>Biometric</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ biometric.id }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ biometric.nombre }}</td>
            </tr>
            <tr>
                <th>C_ojos</th>
                <td>{{ biometric.cOjos }}</td>
            </tr>
            <tr>
                <th>C_cabello</th>
                <td>{{ biometric.cCabello }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_biometric_index') }}">back to list</a>

    <a href="{{ path('app_biometric_edit', {'id': biometric.id}) }}">edit</a>

    {{ include('biometric/_delete_form.html.twig') }}
{% endblock %}